# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)



CaseType.create(name: "AA - Arbitration Application")
CaseType.create(name: "A.C. - Arbitration Cases")
CaseType.create(name: "ACP - ARBITRATION CLAIM PETITION")
CaseType.create(name: "A.I.R.Misc - Accident Information report")
CaseType.create(name: "Appeal -")
CaseType.create(name: "Appl.10(1)(c) - Application u/s 10(1)(c)")
CaseType.create(name: "Appl.10(4)(A) - Application u/s 10(4)(A)")
CaseType.create(name: "Appl.33(2)b - Application u/s 33(2)b")
CaseType.create(name: "APPL.33(C)(2)")
CaseType.create(name: "APPLN - Application for Wakf Board")
CaseType.create(name: "Appl.u/s 11 - Application u/s 11")
CaseType.create(name: "A.S. - Arbitration Suits")
CaseType.create(name: "Caveat -")
CaseType.create(name: "C.C. - CRIMINAL CASES")
CaseType.create(name: "C.O.A. - Company Applications")
CaseType.create(name: "C.O.P. - Company Petitions")
CaseType.create(name: "Cr - Crime Case")
CaseType.create(name: "CRL.A - CRIMINAL APPEAL")
CaseType.create(name: "CRL.M.A. - CRIMINAL MISC.APPEAL")
CaseType.create(name: "Crl.Misc. - CRIMINAL MISC. PETITION")
CaseType.create(name: "CRL.R.P. - CRIMINAL REVISION PETITIONS")
CaseType.create(name: "E.A.T. - Education Appellate Tribunal C")
CaseType.create(name: "ECA - Employees Compensation Applica")
CaseType.create(name: "ELEC.C - ELECTION PETITIONS")
CaseType.create(name: "EX - Execution Petition Under Order")
CaseType.create(name: "Ex.A. - Execution Appeals")
CaseType.create(name: "Ex.C - Execution Cases")
CaseType.create(name: "FDP - Petitioner For Final Decree pr")
CaseType.create(name: "G and WC - Appointment Of Guardian, Other")
CaseType.create(name: "G and W.C. - Guardian and Wards Cases")
CaseType.create(name: "H.R.C. - House Rent Control Cases")
CaseType.create(name: "H.R.C.A. - House Rent Control Appeals")
CaseType.create(name: "I.C. - Insolvency Cases")
CaseType.create(name: "IDact of S10 - Under Sec 10 of ID Act (Ref.Ca")
CaseType.create(name: "IDact of S101d - Industrial Disputes u/s 10(1)(")
CaseType.create(name: "IDact of S.33 - Serial Applications Under Sec.")
CaseType.create(name: "IDact of S332b - Approval Application u/s 33(2)")
CaseType.create(name: "IDact of S33A - Under Sec 33(A) of ID Act (Com")
CaseType.create(name: "IDact of S.A - Complaints under Sec.A of the")
CaseType.create(name: "IID.1947,Sec.32 (A). -")
CaseType.create(name: "Ind Emp of SO Act - Appeal under Industrial Employ")
CaseType.create(name: "J.C. - JUVENILE CASES")
CaseType.create(name: "KID of 104A - KID 10 of 4A")
CaseType.create(name: "L.A.C. - Land Acquisition Cases")
CaseType.create(name: "LAC(APPL) - L.A.C.APPEAL")
CaseType.create(name: "L.P.C. - LONG PENDING CASES")
CaseType.create(name: "M.A. - Miscellanuous Appeals")
CaseType.create(name: "MA(EAT) - Appeal Under Education Act")
CaseType.create(name: "M.C. - MATRIMONIAL CASES")
CaseType.create(name: "Misc - Miscellaneous Cases")
CaseType.create(name: "Misc.Appln. - Miscelleneous Application")
CaseType.create(name: "M.V.C. - Accident Claim Cases u/r M.V.")
CaseType.create(name: "O.L. - OTHER LAW CASES")
CaseType.create(name: "O.S. - Original Suit")
CaseType.create(name: "P and SC - Probate and Succession Cases")
CaseType.create(name: "P and SCert - Petition For Succession Certif")
CaseType.create(name: "P.C.R. - PRIVATE COMPLAINTS")
CaseType.create(name: "P.MIS. - Petition Filed Indegent Person")
CaseType.create(name: "R.A. - Regular Appeals")
CaseType.create(name: "R.C.(E) -")
CaseType.create(name: "REF - References")
CaseType.create(name: "R.P. - REVISION PETITION")
CaseType.create(name: "R.P(Review Petition) - Review Petition")
CaseType.create(name: "R.R.P - Rent Revision Petition")
CaseType.create(name: "SC - SESSION CASES")
CaseType.create(name: "S.C. - Small Cause Suit")
CaseType.create(name: "SPL.C - SPECIAL CASES")
CaseType.create(name: "SPL.C(A.C.Act) - SPECIAL CASES Anti Corruption")
CaseType.create(name: "Spl.Case.IPC and PCR - Special Case(IPC and PCR)")
CaseType.create(name: "SPL.Case(KPTCL) - Special Case(KPTCL)")
CaseType.create(name: "SPL.C(CBI) - CBI CASES")
CaseType.create(name: "SPL.C(Corruptio - SPECIAL CASES (CORRUPTION)")
CaseType.create(name: "SPL.C(E.C.Act) - Special Essential Commodities")
CaseType.create(name: "SPL.C(Elect.) - SPECIAL ELECT. CASES")
CaseType.create(name: "SPL.C(N.D.P.S. - SPECIAL CASES (N.D.P.S. ACT)")
CaseType.create(name: "SPL.C(SC/ST Act - SPECIAL CASES (SC/ST) PA.ACT")
CaseType.create(name: "SPL.C(SVC) - SVC CASES")

State.create(name: "Karnataka")

District.create(name: "BAGALKOT", state_id: 1)
District.create(name: "BALLARI", state_id: 1)
District.create(name: "BELAGAVI", state_id: 1)
District.create(name: "BENGALURU", state_id: 1)
District.create(name: "BENGALURU RURAL", state_id: 1)
District.create(name: "BIDAR", state_id: 1)
District.create(name: "CHAMRAJNAGAR", state_id: 1)
District.create(name: "CHIKKABALLAPUR", state_id: 1)
District.create(name: "CHIKKAMAGALURU", state_id: 1)
District.create(name: "CHITRADURGA", state_id: 1)
District.create(name: "DAKSHINA KANNADA", state_id: 1)
District.create(name: "DAVANGERE", state_id: 1)
District.create(name: "DHARWAD", state_id: 1)
District.create(name: "GADAG", state_id: 1)
District.create(name: "HASSAN", state_id: 1)
District.create(name: "HAVERI", state_id: 1)
District.create(name: "KALABURAGI", state_id: 1)
District.create(name: "KODAGU", state_id: 1)
District.create(name: "KOLAR", state_id: 1)
District.create(name: "KOPPAL", state_id: 1)
District.create(name: "MANDYA", state_id: 1)
District.create(name: "MYSURU", state_id: 1)
District.create(name: "RAICHUR", state_id: 1)
District.create(name: "RAMANAGARAM", state_id: 1)
District.create(name: "SHIVAMOGGA", state_id: 1)
District.create(name: "TUMAKURU", state_id: 1)
District.create(name: "UDUPI", state_id: 1)
District.create(name: "UTTARA KANNADA", state_id: 1)
District.create(name: "VIJAYAPURA", state_id: 1)
District.create(name: "YADGIR", state_id: 1)


# court complexes


CourtComplex.create(name: "Court Complex-Bilagi", state_id: 1, district_id: 1)
CourtComplex.create(name: "Court Complex-Banhatti", state_id: 1, district_id: 1)
CourtComplex.create(name: "Court Complex- Badami", state_id: 1, district_id: 1)
CourtComplex.create(name: "Court Complex- Hungund", state_id: 1, district_id: 1)
CourtComplex.create(name: "Court Complex- Jamkhandi", state_id: 1, district_id: 1)
CourtComplex.create(name: "Court Complex- Mudhol", state_id: 1, district_id: 1)
CourtComplex.create(name: "District Court Complex-Bagalkot", state_id: 1, district_id: 1)

CourtComplex.create(name: "Court Complex- Huvina Hadagali", state_id: 1, district_id: 2)
CourtComplex.create(name: "Court Complex- Hagaribommanahalli", state_id: 1, district_id: 2)
CourtComplex.create(name: "Court Complex- Hospet", state_id: 1, district_id: 2)
CourtComplex.create(name: "Court Complex- Kudligi", state_id: 1, district_id: 2)
CourtComplex.create(name: "Court Complex- Sandur", state_id: 1, district_id: 2)
CourtComplex.create(name: "Court Complex- Siruguppa", state_id: 1, district_id: 2)
CourtComplex.create(name: "District Court Complex-Ballari", state_id: 1, district_id: 2)

CourtComplex.create(name: "Court Complex-Athani", state_id: 1, district_id: 3)
CourtComplex.create(name: "Court Complex-Bailhongal", state_id: 1, district_id: 3)
CourtComplex.create(name: "Court Complex- Hukkeri", state_id: 1, district_id: 3)
CourtComplex.create(name: "Court Complex- Khanapur", state_id: 1, district_id: 3)
CourtComplex.create(name: "Court Complex- Nipani", state_id: 1, district_id: 3)
CourtComplex.create(name: "Court Complex- Raibag", state_id: 1, district_id: 3)
CourtComplex.create(name: "Court Complex- Ramdurga", state_id: 1, district_id: 3)
CourtComplex.create(name: "Court Complex- sankeshwar", state_id: 1, district_id: 3)
CourtComplex.create(name: "Court Complex- Saundatti", state_id: 1, district_id: 3)
CourtComplex.create(name: "District (Old) Court Complex-Belagavi", state_id: 1, district_id: 3)
CourtComplex.create(name: "New Court Complex-Belagavi", state_id: 1, district_id: 3)

CourtComplex.create(name: "City Civil Court Complex, Bangalore", state_id: 1, district_id: 4)
CourtComplex.create(name: "CMM Court Complex, Bangalore", state_id: 1, district_id: 4)
CourtComplex.create(name: "Mayo Hall Court Complex, Bangalore", state_id: 1, district_id: 4)

CourtComplex.create(name: "Court Complex- Anekal", state_id: 1, district_id: 5)
CourtComplex.create(name: "Court Complex- Doddaballapur", state_id: 1, district_id: 5)
CourtComplex.create(name: "Court Complex- Hosakote", state_id: 1, district_id: 5)
CourtComplex.create(name: "Court Complex- Nelamangala", state_id: 1, district_id: 5)
CourtComplex.create(name: "City Civil Court Complex-Bengalurur Rual", state_id: 1, district_id: 5)

CourtComplex.create(name: "Court Complex-Basavakalyan", state_id: 1, district_id: 6)
CourtComplex.create(name: "Court Complex-Bhalki", state_id: 1, district_id: 6)
CourtComplex.create(name: "Court Complex-Humnabad", state_id: 1, district_id: 6)
CourtComplex.create(name: "Court Complex-Aurad", state_id: 1, district_id: 6)
CourtComplex.create(name: "District Court Complex-Bidar", state_id: 1, district_id: 6)

CourtComplex.create(name: "Court Complex- Gundlupet", state_id: 1, district_id: 7)
CourtComplex.create(name: "Court Complex- Kollegal", state_id: 1, district_id: 7)
CourtComplex.create(name: "Court Complex- Yelandur", state_id: 1, district_id: 7)
CourtComplex.create(name: "District Court Complex-Chamarajanagar", state_id: 1, district_id: 7)

CourtComplex.create(name: "Court Complex-Bagepalli", state_id: 1, district_id: 8)
CourtComplex.create(name: "JMFC Court Complex-Chintamani", state_id: 1, district_id: 8)
CourtComplex.create(name: "Court Complex- Gowribidanur", state_id: 1, district_id: 8)
CourtComplex.create(name: "Court Complex- Sidlaghatta", state_id: 1, district_id: 8)
CourtComplex.create(name: "District Court Complex-Chikkaballapur", state_id: 1, district_id: 8)
CourtComplex.create(name: "COURT COMPLEX - GUDIBANDA", state_id: 1, district_id: 8)

CourtComplex.create(name: "Court Complex-Koppa", state_id: 1, district_id: 9)
CourtComplex.create(name: "Court Complex-Kadur", state_id: 1, district_id: 9)
CourtComplex.create(name: "Court Complex-Mudigere", state_id: 1, district_id: 9)
CourtComplex.create(name: "Court Complex-N.R.Pura", state_id: 1, district_id: 9)
CourtComplex.create(name: "Court Complex-Tarikere", state_id: 1, district_id: 9)
CourtComplex.create(name: "Court Complex-Sringeri", state_id: 1, district_id: 9)
CourtComplex.create(name: "District Court Complex-Chikkamagalur", state_id: 1, district_id: 9)

CourtComplex.create(name: "Court Complex-Challakere", state_id: 1, district_id: 10)
CourtComplex.create(name: "Court Complex-Hiriyur", state_id: 1, district_id: 10)
CourtComplex.create(name: "Court Complex-Hosadurga", state_id: 1, district_id: 10)
CourtComplex.create(name: "Court Complex-Molakalmuru", state_id: 1, district_id: 10)
CourtComplex.create(name: "District Court Complex-Chitradurga", state_id: 1, district_id: 10)

